# Site settings
title: Open Chattanooga
email: info@openchattanooga.com
description: ""
baseurl: ""
url: "http://openchattanooga.com"

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
