# Site settings
title: Open Chattanooga
email: info@openchattanooga.com
description: "Advocating for open local public data and supporting the geeks and civic hackers who make it useful!"
url: "http://openchattanooga.com"

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
paginate: 5
paginate_path: "blog/page:num"

sass:
    sass_dir: _scss
    style: :compressed

# Open Graph
og_image: img/mark-fb.png # Default image for Open Graph tag
og_image_type: image/png
og_image_width: 250
og_image_height: 250
fb_profile_id: OpenChattanooga
fb_admins: 57701055

gems:
  - jekyll-sitemap
