# Site settings
title: Open Chattanooga
email: info@openchattanooga.com
description: ""
baseurl: ""
url: "/"

# Build settings
markdown: kramdown
permalink: pretty
highlights: false

sass:
    sass_dir: _scss

exclude:
    -   bower_components
    -   node_modules
    -   sass
