# Site settings
title: Open Chattanooga
email: info@openchattanooga.com
description: ""
baseurl: "/openchattanooga.github.io"
url: "http://openchattanooga.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   sass
