# Site settings
title: Open Chattanooga
email: info@openchattanooga.com
description: "Advocating for open local public data and supporting the geeks and civic hackers who make it useful!"
url: "http://openchattanooga.com"

# Build settings
markdown: kramdown
permalink: pretty
highlights: false

sass:
    sass_dir: _scss
    style: :compressed
